@startuml

    !include ./stylesheet.puml

    package IndividualLevel{
        class User<<main>>{
            **id** — UUID
            **email** — string
            **organisationId** — UUID
            **officeSpaceId** — UUID
            **currentStatus()** — latest UserStatusChange record
        }

        class UserStatus{
            **id** — UUID
            **label** — string
            **isActive** — boolean
        }
        note top of UserStatus
            Possible statuses
        endnote


        class UserStatusChange{
            **id** — UUID
            **userId** — UUID
            **userStatusId** — UUID
            **recordDate** — Date
        }
        note top of UserStatusChange
            Every status change
        endnote

        class CircleMembership{
            **id** — UUID
            **userId** — UUID
            **teamId** — UUID
            **status** — UUID
            **type** — UUID
            **startDate** — Date
            **endDate** — Date
        }
        note top of CircleMembership
            Optional membership
            of the organisation's
            users
        endnote

        class CircleMembershipStatus{
            **id** — UUID
            **label** — string
            **isActive** — boolean
        }

        class CircleMembershipType{
            **id** — UUID
            **label** — string
        }

        CircleMembership --- CircleMembershipStatus
        CircleMembership -- CircleMembershipType
    }

    package OrganisationLevel {
        class Organisation<<main>>{
            **id** — UUID
            **planId** — UUID
            **isActive** — boolean
        }
        note right of Organisation
            Partner Company
            Group which collects
            teams and users
        endnote

        class Circle{
            **id** — UUID
            **organisationId** — UUID
            **name** — string
        }
        note left of Circle
            Circles inside
            an <b>Organisation</b>
            Acts as a team
        endnote

        class Plan{
            **id** — UUID
            **name** — string
            **validFrom** — Date
            **validUntil** — Date
            **cost** — money
        }
        note right of Plan
            Paying plan of
            an <b>Organisation</b>
        endnote
    }

    package ProfileLevel {
        class ProfileElement{
            **id** — UUID
            **organisationId** — UUID
            **label** — string
            **typeId** — UUID
            **options** — string[]
            **isOptional** — boolean
            **isActive** — boolean
        }
        note right of ProfileElement
            1 Profile element what
            organisation members
            can set on their profile
        endnote

        class ProfileElementType{
            **id** — UUID
            **label** — string
        }
        note right of ProfileElementType
            Possible elements to choose from
        endnote

        class UserProfileElement{
            **id** — UUID
            **userId** — UUID
            **profileElementId** — UUID
        }
        note right of UserProfileElement
            Extension of user's
            personal profile
            with dynamic elements
        endnote

        User -- UserProfileElement
        UserProfileElement -- ProfileElement
        ProfileElement -- ProfileElementType
        ProfileElement - Organisation
    }

    ' helper arrow for package alignment
    'IndividualLevel ---d[hidden]--> OrganisationLevel

    User -- Organisation
    UserStatusChange -- User
    UserStatusChange - UserStatus
    Organisation -- Plan
    Organisation -- Circle
    CircleMembership - Circle
    CircleMembership - User

@enduml
